// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OkulTakipSistemi.Data;

#nullable disable

namespace OkulTakipSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822120340_OgrenciAktifEklendi")]
    partial class OgrenciAktifEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OkulTakipSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SinifId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SinifId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgrenciKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OkulId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SinifId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("OkulId");

                    b.HasIndex("SinifId");

                    b.ToTable("OgrenciKayitlari");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgrenciUcretDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndirimOrani")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Indirimli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciKaydiId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OzelFiyat")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ucretsiz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciKaydiId");

                    b.ToTable("OgrenciUcretDurumlari");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgrenciVeli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeliId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("VeliId");

                    b.ToTable("OgrenciVeliler");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Ogretmen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branş")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgretmenSinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SinifId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OgretmenId");

                    b.HasIndex("SinifId");

                    b.ToTable("OgretmenSiniflar");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Okul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Okullar");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OkulUcreti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AylikUcret")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GecerlilikTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OkulId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OkulId");

                    b.ToTable("OkulUcretleri");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Sinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OkulId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OkulId");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Veli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Yakinlik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veliler");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Yoklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SinifId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OgretmenId");

                    b.HasIndex("SinifId");

                    b.ToTable("Yoklamalar");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.YoklamaDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Geldi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YoklamaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("YoklamaId");

                    b.ToTable("YoklamaDetaylari");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Kullanici", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Odeme", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Ogrenci", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgrenciKaydi", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OkulTakipSistemi.Models.Okul", "Okul")
                        .WithMany()
                        .HasForeignKey("OkulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OkulTakipSistemi.Models.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Okul");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgrenciUcretDurumu", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.OgrenciKaydi", "OgrenciKaydi")
                        .WithMany()
                        .HasForeignKey("OgrenciKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgrenciKaydi");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgrenciVeli", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OkulTakipSistemi.Models.Veli", "Veli")
                        .WithMany("OgrenciVeliler")
                        .HasForeignKey("VeliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Veli");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Ogretmen", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OgretmenSinif", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Ogretmen", "Ogretmen")
                        .WithMany()
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OkulTakipSistemi.Models.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogretmen");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.OkulUcreti", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Okul", "Okul")
                        .WithMany()
                        .HasForeignKey("OkulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Okul");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Sinif", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Okul", "Okul")
                        .WithMany()
                        .HasForeignKey("OkulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Okul");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Yoklama", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Ogretmen", "Ogretmen")
                        .WithMany()
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OkulTakipSistemi.Models.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogretmen");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.YoklamaDetay", b =>
                {
                    b.HasOne("OkulTakipSistemi.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OkulTakipSistemi.Models.Yoklama", "Yoklama")
                        .WithMany("Detaylar")
                        .HasForeignKey("YoklamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Yoklama");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Veli", b =>
                {
                    b.Navigation("OgrenciVeliler");
                });

            modelBuilder.Entity("OkulTakipSistemi.Models.Yoklama", b =>
                {
                    b.Navigation("Detaylar");
                });
#pragma warning restore 612, 618
        }
    }
}
